--- 
cashe: npm
deploy: 
  github_token: $TOKEN
  keep_history: true
  local_dir: build
  provider: pages
  skip_cleanup: true
  true: 
    branch: master
env: 
  - 
    PORT: 3000
install: "npm ci"
language: node_js
node_js: "12.16.3"
script: 
  - "npm test"
  - "npm run build"